org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
forge_version=52.1.0
forge_version_range=[52,53)
loader_version_range=[52,)
mapping_channel=official
mapping_version=1.21.1

mod_id=playitproxyprotocol
mod_name=Playit Proxy Protocol
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.dany.playitproxyprotocol
mod_authors=Dany
mod_description=Server-side HAProxy Proxy Protocol v1/v2 support for Minecraft Forge servers behind playit.gg.
